[rabbit]
host = "127.0.0.1" #default: "localhost"
port = 5672 #default: 5672
login = "owt"
password= "owt"

[mongo]
dataBaseURL = "127.0.0.1/owtdb" #default: "localhost/owtdb"

[cluster]
name = "owt-cluster"