[server]
keystorePath = "./cert/certificate.pfx"
superserviceID = "_auto_generated_ID_" #default: ""
ssl = true #if use HTTPS
port = 3000 #default: 3000, port of server
numberOfProcess = 4 #default: 1

[cluster]
name = "owt-cluster"

[rabbit]
host = "192.168.72.140" #default: "localhost"
port = 5672 #default: 5672
login = "owt"
password = "owt"

[mongo]
dataBaseURL = "localhost/owtdb" #default: "localhost/owtdb"