[rabbit]
host = "172.31.40.148" #default: "localhost"
port = 5672 #default: 5672
login = "owt"
password= "owt"

[mongo]
dataBaseURL = "172.31.40.148/owtdb" #default: "localhost/owtdb"

[cluster]
name = "owt-cluster"